# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Transforming the Afro-Caribbean World
tagline:          'Digital Methods Mini-Site'
description:      'Notes on sources and methods'
url:              http://umd-mith.github.io/taw_workshop
baseurl:          /taw_workshop/

author:
  name:           'Trevor Mu√±oz'
  url:            https://twitter.com/trevormunoz

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
